/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
import java.util.Arrays;
import java.util.List;


public class App {
    public static void main(String[] args) {
        // Creation chapitres
        Chapitre chapitre1 = new Chapitre("Introduction", Arrays.asList("Page 1", "Page 2"));
        Chapitre chapitre2 = new Chapitre("Développement", Arrays.asList("Page 3", "Page 4", "Page 5"));

        // Création  mémoire avec ces chapitres
        List<Chapitre> chapitres = Arrays.asList(chapitre1, chapitre2);
        Memoire memoire = new Memoire("Mémoire de Master", chapitres);


        System.out.println("Titre du mémoire : " + memoire.titre());
        System.out.println("Nombre total de pages : " + memoire.taille());
    }
}
