/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


import org.junit.Test;
import static org.junit.Assert.*;
import java.util.Arrays;

public class AppTest {
    @Test
    public void testTailleMemoire() {
        // Créer des chapitres
        Chapitre chapitre1 = new Chapitre("Introduction", Arrays.asList("Page1", "Page2"));
        Chapitre chapitre2 = new Chapitre("Patrons", Arrays.asList("Page1", "Page2", "Page3"));
        Chapitre chapitre3 = new Chapitre("Anti-Patrons", Arrays.asList("Page1", "Page2"));
        Chapitre chapitre4 = new Chapitre("Conclusion", Arrays.asList("Page1"));

        // Créer un mémoire avec les chapitres
        Memoire memoireAlice = new Memoire("Patrons et Anti-Patrons", Arrays.asList(chapitre1, chapitre2, chapitre3, chapitre4));

        // Vérifier que la taille du mémoire (nombre total de pages) est correcte
        assertEquals("La taille du mémoire devrait être 7", 7, memoireAlice.taille());
    }
}
